# This project requires the following ruby gems, buildr addons
gems:
  # Enhance pom generation by adding dependencies
  - buildr-dependency-extensions
  
repositories:
  remote: 
    - http://repo1.maven.org/maven2
    
junit: 4.8.1
jmock: 2.5.1
